<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="70" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="70" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
      <class name="p2.Test4">
        <test-method status="PASS" signature="Launch_URL()[pri:0, instance:p2.Test4@5034c75a]" name="Launch_URL" is-config="true" duration-ms="11" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch_URL -->
        <test-method status="PASS" signature="login()[pri:0, instance:p2.Test4@5034c75a]" name="login" is-config="true" duration-ms="0" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="m10()[pri:0, instance:p2.Test4@5034c75a]" name="m10" duration-ms="12" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Age Criteria not satisfied expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Age Criteria not satisfied expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at p2.Test4.m10(Test4.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m10 -->
        <test-method status="PASS" signature="Logout()[pri:0, instance:p2.Test4@5034c75a]" name="Logout" is-config="true" duration-ms="1" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method status="PASS" signature="m11()[pri:0, instance:p2.Test4@5034c75a]" name="m11" duration-ms="3" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m11 -->
        <test-method status="PASS" signature="login()[pri:0, instance:p2.Test4@5034c75a]" name="login" is-config="true" duration-ms="0" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="Logout()[pri:0, instance:p2.Test4@5034c75a]" name="Logout" is-config="true" duration-ms="1" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method status="PASS" signature="Close_Browser()[pri:0, instance:p2.Test4@5034c75a]" name="Close_Browser" is-config="true" duration-ms="1" started-at="2020-02-15T06:29:01Z" finished-at="2020-02-15T06:29:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close_Browser -->
      </class> <!-- p2.Test4 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
